apiVersion: v1
kind: Service
metadata:
  name: nextjs-helloworld-service
  namespace: default # Match the namespace of the Deployment
spec:
  selector:
    app: nextjs-helloworld # Selects pods with this label
  ports:
    - protocol: TCP
      port: 80       # Port the service listens on
      targetPort: 3000 # Port the container listens on
  type: ClusterIP # Use LoadBalancer if you need external access via a cloud provider LB, or NodePort for direct node access 